config/routes.rb
Rails.application.routes.draw do
  root to: "dashboard#show"
  resources :users
	resources :books

	resources :clubs do
		resources :books
	end
	
	resources :clubs do
		member do
			post :join
		end
	end

  get "/login", to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :club
end

app/models/book_info.rb
class BookInfo 

	def initialize(book_atts={})
		@title = book_atts[:volumeInfo][:title]
		@author = book_atts[:volumeInfo][:authors]
		@description = book_atts[:volumeInfo][:description]
		binding.pry
	end

	def self.b_info(isbn)
		GoogleService.new.isbn_info(isbn)[:items].map do |b|
			BookInfo.new(b)
		end
	end
end

app/models/club.rb
class Club < ApplicationRecord
	has_many :club_users
	has_many :users, through: :club_users
	has_many :books
end

app/models/club_user.rb
class ClubUser < ApplicationRecord
  belongs_to :club
  belongs_to :user
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
	has_many :club_users
	has_many :clubs, through: :club_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
	helper_method :current_user, :require_login, :logged_in?
	before_action :require_login

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

	private

	def logged_in?
		!current_user.nil?
	end

	def require_login
		unless logged_in?
			flash[:error] = "You must be logged in"
			redirect_to root_path
		end
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	def new
		@club = Club.find(params[:club_id])
		@book = Book.new()
	end

	def index
		@club = Club.find(params[:club_id])
		@books = @club.books
		@book = Book.new
	end

	def create
		@club = Club.find(params[:club_id])
		@book = @club.books.new(book_params)
		if @book.save
			flash[:success] = "You created a book"
			redirect_to club_book_path(@club, @book)
		else
			render :new
		end
	end

	def show
		@club = Club.find(params[:club_id])
		@book = Book.find(params[:id])
	end

	private

	def book_params
		params.require(:book).permit(:title, :author, :description, :isbn)
	end

end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController

	def new
	end

	def create
		@club = current_user.clubs.new(club_params)
		@club.creator = current_user.username if current_user
		if @club.save
			redirect_to club_path(@club)
		else
			render :new
		end
	end

	def index
		@club = Club.all
	end

	def show
		@club = Club.find(params[:id])
	end

	def join
		@club = Club.find(params[:id])
		current_user.clubs << @club
		redirect_to @club
	end

	private

	def club_params
		params.require(:club).permit(:name, :description, :creator)
	end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	def show
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:notice] = "Successful Login"
      redirect_to root_path

    else
      flash[:notice] = "Invalid Credentials"
      redirect_to login_path
    end
  end

	def destroy
		session[:user_id] = nil
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome, #{@user.username}"
      redirect_to login_path
    else
      flash[:notice] = "Invalid Credentials"
      redirect_to new_user_path
    end
  end


  private

  def user_params
    params.require(:user).permit(:username, :password, :first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
<%= @club.name %>

<% @books.each do |book| %>
	<%= book.title %>
<% end %>

<h3><%= link_to "create a book", new_club_book_path(@club, @book) %></h3>

app/views/books/new.html.erb
<h1>Create a book for <%= @club.name %></h1>

<h1>Create a Book</h1>

<%= form_for [@club, @book] do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>

	<%= f.label :author %>
	<%= f.text_field :author %>

	<%= f.label :description %>
	<%= f.text_field :description %>

	<%= f.label :isbn %>
	<%= f.text_field :isbn %>

	<%= f.submit "Create Book" %>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.title %>

app/views/clubs/index.html.erb
<% @club.each do |f| %>
	<%= link_to f.name, club_path(f) %>
	<%= f.description %>
<% end %>

app/views/clubs/new.html.erb
<h1> Create a Book Club </h1>

<%= form_for(:club, url: clubs_path) do |f|%>
	<%= f.label 'name'  %>
	<%= f.text_field :name %>

	<%= f.label 'description' %>
	<%= f.text_field :description %>

	<%= f.submit 'Create Book Club' %>
	<% end%>
	
	

app/views/clubs/show.html.erb
<h1><%= @club.name %></h1>
<% unless current_user.clubs.include?(@club) %>
	<%= button_to 'Join Club', join_club_path(@club.id), :method => :post%>
<% end %>

<% if current_user.username == @club.creator %>
	<%= link_to "Create Poll" %>
<% end %>

<%= link_to "View Books", club_books_path(@club) %>

<% @club.books.each do |f| %>
	<%= f.title %>
<% end %>

app/views/dashboard/show.html.erb
<h1>Welcome to Book Club</h1>
<%= link_to "View Clubs", clubs_path %>
<footer>
<% unless current_user %>
	<%= link_to "Sign Up", new_user_path %>
<% end %>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookClub</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

	

  <body>
    <%= yield %>
  </body>
	<footer>
		<% if current_user %>
			<%= current_user.username %>
			<%= link_to "Logout", logout_path, method: :delete %>
	<% end %>
	</footer>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for(:user, url: users_path) do |f| %>
  <%= f.label 'username' %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.submit "Create Account" %>
<% end %>